### ISSUE TITLE
too large elastic buffer or elastic buffer incoherent structure

### ISSUE THREAD

**Issue by bonanza123** [peckto/gdar#3]
Hello,

I'm using gdar on archlinux (compiled from this repo with `enable-libdar64`) and tried to open a splitted (each 1GB) and encrypted dar archive. After entering the password is says `too large elastic buffer or elastic buffer incoherent structure` and doesn't show any files.

The archive has been created with 
```
% dar --version

 dar version 2.5.8, Copyright (C) 2002-2052 Denis Corbin
   Long options support       : YES

 Using libdar 5.8.4 built with compilation time options:
   Libz compression (gzip)      : YES
   Libbz2 compression (bzip2)   : YES
   Liblzo2 compression (lzo)    : YES
   Liblzma compression (xz)     : YES
   Strong encryption (libgcrypt): YES
   Public key ciphers (gpgme)   : YES
   Extended Attributes support  : YES
   Large files support (> 2GB)  : YES
   ext2fs NODUMP flag support   : YES
   Special allocation scheme    : NO
   Integer size used            : 64 bits
   Thread safe support          : YES
   Furtive read mode support    : YES
   Linux ext2/3/4 FSA support   : YES
   Mac OS X HFS+ FSA support    : NO
   Detected system/CPU endian   : little
   Posix fadvise support        : YES
   Large dir. speed optimi.     : YES
   Timestamp read accuracy      : 1 microsecond
   Timestamp write accuracy     : 1 microsecond
   Restores dates of symlinks   : YES

 compiled the Jan 23 2017 with GNUC version 6.3.1 20170109
 dar is part of the Disk ARchive suite (Release 2.5.8)
 dar comes with ABSOLUTELY NO WARRANTY; for details
 type `dar -W'. This is free software, and you are welcome
 to redistribute it under certain conditions; type `dar -L | more'
 for details.
```

Maybe I should add that `autogen` issued the following error upon building (which nevertheless worked fine):
```
% ./autogen.sh
configure.ac:25: installing './compile'
configure.ac:7: installing './install-sh'
configure.ac:7: installing './missing'
configure.ac:9: error: required file 'config.h.in' not found
src/Makefile.am: installing './depcomp'
```

Edit: For the sake of completeness: `dar -l ` works on the archive

**Comment by peckto** [comment]
Hi,

The error indicates a problem with the encryption settings.

At the moment, encrypted dar archives are not recognized automatically by gdar.
If you wont to open an encrypted archive, you must select the "Backup is encrypted" option in the open dialog. In the dialog "Encryption settings" you can then enter your encryption settings and the key.

Please note: 
- default encryption algorithm used by dar: blowfish 
- default block size: 1024

If you have not changed these setting when creating the backup, that's what you have to enter.

Please also note: gdar does not support gnupg encrypted dar archives at the moment.

I hope that solves you problem.

**Comment by bonanza123** [comment]
@peckto  thanks a lot for the info. I already wondered about the encryption algorithm, so I sticked to gdar's default (AES). Maybe you could make blowfish also the default in gdar?

Selecting Blowfish solved the problem, thanks!
