### ISSUE TITLE
"Show Hidden Files" switch visual bug

### ISSUE THREAD

**Issue by MrVoltz** [peckto/gdar#9]
I've compiled latest master, it works ok, but the toolbar is stretched and it doesn't look nice. Thanks for maintaining this, it works and is fast unlike DarGUI.

![Screenshot from 2021-05-06 14-41-09](https://user-images.githubusercontent.com/5212649/117299976-642eda00-ae79-11eb-86d4-ed7bb3e75398.png)

**Comment by peckto** [comment]
Hi MrVoltz, 
Thanks for your feedback. 
The UI is not yet optimized for resizing the window.
The widgets are auto-sized, which causes the stretched look.
I will have a look at this.
Best regards
Tobias

**Comment by peckto** [comment]
I created a MR to aligned the buttons to the left and set a fixed width: #13 
How does this look on your system?

**Comment by MrVoltz** [comment]
Thank you for the quick fix. It is better, but the switch is still stretched. The controls could also use some horizontal and vertical padding. Also it would be good to put some label next to the toggle switch, so you don't have to hover it to see the tooltip.

If you don't want to bother with these little things, just close the issue and call it a day :)
![Screenshot from 2021-05-08 21-52-09](https://user-images.githubusercontent.com/5212649/117551779-2df38500-b048-11eb-8dd8-643afb6c84ba.png)

**Comment by peckto** [comment]
Thanks for you feedback. 
The "show hidden files" switch always caused me trouble ^^
I now replaced it by a check box. 
Do you think this makes it more intuitive?

**Comment by MrVoltz** [comment]
Hi, thanks for the update. I think that now it is perfect, both more intuitive and without visual glitches. Thank you for the fix :+1: 

![Screenshot from 2021-05-09 23-32-17](https://user-images.githubusercontent.com/5212649/117587581-fc99b880-b11e-11eb-8e87-97cc2dec365f.png)

**Comment by peckto** [comment]
Perfect. Your welcome.
